// 大学受験頻出英単語リスト
// 共通テスト・難関大入試の出題傾向を統計的に分析した独自編集リスト
// 形式: [英語, 日本語, 発音記号]

const EXAM_LISTS = [

  // ════════════════════════════════
  //  初級編  共通テスト基礎レベル
  // ════════════════════════════════
  {
    id: 'exam-basic',
    name: '共通テスト 基礎',
    icon: 'book-open',
    color: '#064e3b',
    description: '共通テストで頻出の基礎単語。まずここからマスターしよう。',
    words: [
      // 動詞
      ['use','使う','júːz'],
      ['make','作る、させる','méik'],
      ['give','与える','gív'],
      ['get','得る、なる','gét'],
      ['take','取る、かかる','téik'],
      ['come','来る','kʌ́m'],
      ['go','行く','góu'],
      ['know','知っている','nóu'],
      ['think','考える','θíŋk'],
      ['find','見つける','fáind'],
      ['see','見る、わかる','síː'],
      ['look','見る','lúk'],
      ['want','欲しい','wɑ́nt'],
      ['become','〜になる','bikʌ́m'],
      ['show','示す','ʃóu'],
      ['feel','感じる','fíːl'],
      ['leave','去る、残す','líːv'],
      ['bring','持ってくる','bríŋ'],
      ['begin','始まる','bigín'],
      ['keep','保つ','kíːp'],
      ['hold','持つ、開催する','hóuld'],
      ['turn','向ける、回転する','tə́ːrn'],
      ['follow','従う','fɑ́lou'],
      ['move','動く、感動させる','múːv'],
      ['live','生きる、住む','lív'],
      ['work','働く、機能する','wə́ːrk'],
      ['run','走る、運営する','rʌ́n'],
      ['write','書く','ráit'],
      ['set','設定する','sét'],
      ['call','呼ぶ、電話する','kɔ́ːl'],
      ['need','必要とする','níːd'],
      ['try','試みる','trái'],
      ['ask','尋ねる、頼む','ǽsk'],
      ['put','置く','pút'],
      ['say','言う','séi'],
      ['tell','伝える','tél'],
      ['mean','意味する','míːn'],
      ['learn','学ぶ','lə́ːrn'],
      ['appear','現れる','əpíər'],
      ['continue','続ける','kəntínjuː'],
      ['allow','許可する','əláu'],
      ['include','含む','inklúːd'],
      ['change','変える','tʃéindʒ'],
      ['happen','起こる','hǽpən'],
      ['grow','成長する','gróu'],
      ['add','加える','ǽd'],
      ['offer','提供する','ɑ́fər'],
      ['provide','提供する','prəváid'],
      ['help','助ける','hélp'],
      ['reach','到達する','ríːtʃ'],
      ['speak','話す','spíːk'],
      ['meet','会う','míːt'],
      ['open','開く','óupən'],
      ['create','創る','kriéit'],
      ['produce','生産する','prədjúːs'],
      ['cause','引き起こす','kɔːz'],
      ['support','支援する','səpɔ́ːrt'],
      ['lead','導く','líːd'],
      ['form','形成する','fɔːrm'],
      ['develop','発展する','divéləp'],
      ['read','読む','ríːd'],
      ['understand','理解する','ʌ̀ndərstǽnd'],
      ['require','必要とする','rikwáiər'],
      ['increase','増加する','inkríːs'],
      ['suggest','提案する','səgdʒést'],
      ['consider','考慮する','kənsídər'],
      ['play','演じる、遊ぶ','pléi'],
      ['return','戻る','ritə́ːrn'],
      ['lose','失う、負ける','lúːz'],
      ['pass','通過する','pǽs'],
      ['spend','費やす','spénd'],
      ['send','送る','sénd'],
      ['choose','選ぶ','tʃúːz'],
      ['win','勝つ','wín'],
      ['raise','上げる、育てる','réiz'],
      ['receive','受け取る','risíːv'],
      ['pay','支払う','péi'],
      ['wait','待つ','wéit'],
      ['remember','覚えている','rimémbər'],
      ['start','始める','stɑ́ːrt'],
      ['stop','止まる、やめる','stɑ́p'],
      ['end','終わる','énd'],
      ['stay','とどまる','stéi'],
      ['fall','落ちる','fɔ́ːl'],
      ['enjoy','楽しむ','indʒɔ́i'],
      ['care','気にかける','kέər'],
      ['hope','望む','hóup'],
      ['close','閉じる','klóuz'],
      ['believe','信じる','bilíːv'],
      ['lose','失う','lúːz'],
      ['break','壊す','bréik'],
      ['explain','説明する','ikspléin'],
      ['describe','描写する','diskráib'],
      ['decide','決める','disáid'],
      ['protect','保護する','prətékt'],
      ['reduce','減らす','ridjúːs'],
      ['improve','改善する','imprúːv'],
      ['accept','受け入れる','əksépt'],
      ['affect','影響する','əfékt'],
      // 名詞
      ['time','時間','táim'],
      ['year','年','jíər'],
      ['way','方法、道','wéi'],
      ['day','日','déi'],
      ['people','人々','píːpl'],
      ['life','生活、人生','láif'],
      ['world','世界','wə́ːrld'],
      ['hand','手','hǽnd'],
      ['place','場所','pléis'],
      ['case','場合、事例','kéis'],
      ['week','週','wíːk'],
      ['company','会社','kʌ́mpəni'],
      ['number','数','nʌ́mbər'],
      ['part','部分','pɑ́ːrt'],
      ['fact','事実','fǽkt'],
      ['information','情報','ìnfərméiʃən'],
      ['thing','もの、こと','θíŋ'],
      ['problem','問題','prɑ́bləm'],
      ['country','国','kʌ́ntri'],
      ['school','学校','skúːl'],
      ['food','食べ物','fúːd'],
      ['water','水','wɔ́ːtər'],
      ['city','都市','síti'],
      ['home','家、故郷','hóum'],
      ['family','家族','fǽməli'],
      ['money','お金','mʌ́ni'],
      ['book','本','búk'],
      ['health','健康','hélθ'],
      ['body','身体','bɑ́di'],
      ['mind','心、精神','máind'],
      ['area','地域、面積','έəriə'],
      ['job','仕事','dʒɑ́b'],
      ['group','グループ','grúːp'],
      ['word','単語、言葉','wə́ːrd'],
      ['point','点、要点','pɔ́int'],
      ['question','質問','kwéstʃən'],
      ['idea','考え','aidíə'],
      ['result','結果','rizʌ́lt'],
      ['example','例','igzǽmpl'],
      ['child','子ども','tʃáild'],
      ['reason','理由','ríːzən'],
      ['need','必要','níːd'],
      ['change','変化','tʃéindʒ'],
      ['interest','興味、利子','íntrəst'],
      ['name','名前','néim'],
      ['language','言語','lǽŋgwidʒ'],
      ['country','国','kʌ́ntri'],
      ['power','力、電力','páuər'],
      ['society','社会','səsáiəti'],
      ['nature','自然','néitʃər'],
      ['age','年齢、時代','éidʒ'],
      ['story','話、物語','stɔ́ːri'],
      ['line','線、列','láin'],
      ['research','研究','risə́ːrtʃ'],
      ['difference','違い','dífərəns'],
      ['opportunity','機会','ɑ̀pərtjúːnəti'],
      ['experience','経験','ikspíəriəns'],
      ['knowledge','知識','nɑ́lidʒ'],
      ['effect','効果、影響','ifékt'],
      ['process','過程','prɑ́ses'],
      ['role','役割','róul'],
      ['system','システム','sístəm'],
      ['environment','環境','invái(ə)rnmənt'],
      ['level','水準','lévəl'],
      ['value','価値','vǽljuː'],
      ['issue','問題、課題','íʃuː'],
      // 形容詞・副詞
      ['good','良い','gúd'],
      ['new','新しい','njúː'],
      ['first','最初の','fə́ːrst'],
      ['last','最後の','lǽst'],
      ['long','長い','lɔ́ŋ'],
      ['great','すばらしい','gréit'],
      ['little','小さい、少し','lítl'],
      ['own','自分自身の','óun'],
      ['old','古い、年老いた','óuld'],
      ['right','正しい','ráit'],
      ['large','大きい','lɑ́ːrdʒ'],
      ['next','次の','nékst'],
      ['early','早い','ə́ːrli'],
      ['young','若い','jʌ́ŋ'],
      ['important','重要な','impɔ́ːrtənt'],
      ['different','異なる','dífərənt'],
      ['possible','可能な','pɑ́səbl'],
      ['real','現実の','ríəl'],
      ['able','〜できる','éibl'],
      ['true','本当の','trúː'],
      ['free','自由な、無料の','fríː'],
      ['main','主な','méin'],
      ['sure','確かな','ʃúər'],
      ['high','高い','hái'],
      ['common','一般的な','kɑ́mən'],
      ['social','社会的な','sóuʃəl'],
      ['natural','自然の','nǽtʃərəl'],
      ['human','人間の','hjúːmən'],
      ['various','さまざまな','vέəriəs'],
      ['necessary','必要な','nésəsèri'],
      ['local','地元の','lóukəl'],
      ['general','一般的な','dʒénərəl'],
      ['recent','最近の','ríːsnt'],
      ['already','すでに','ɔːlrédi'],
      ['often','しばしば','ɔ́ːfən'],
      ['always','いつも','ɔ́ːlweiz'],
      ['usually','通常','júːʒuəli'],
      ['probably','おそらく','prɑ́bəbli'],
      ['however','しかしながら',''],
      ['also','また、〜も','ɔ́ːlsou'],
      ['still','まだ、静かな','stíl'],
      ['only','ただ〜だけ','óunli'],
      ['even','〜でさえ','íːvən'],
      ['finally','最終的に','fáinəli'],
      ['especially','特に','ispéʃəli'],
      ['enough','十分な','ináf'],
      ['together','一緒に','təgéðər'],
      ['almost','ほとんど','ɔ́ːlmoust'],
      ['actually','実は','ǽktʃuəli'],
      ['already','すでに','ɔːlrédi'],
      ['simply','単純に','símpli'],
    ]
  },

  // ════════════════════════════════
  //  中級編  私大標準・共通テスト高得点
  // ════════════════════════════════
  {
    id: 'exam-intermediate',
    name: '私大標準 中級',
    icon: 'graduation-cap',
    color: '#1e3a5f',
    description: 'MARCH・関関同立レベルの頻出単語。共通テスト高得点にも必須。',
    words: [
      // 動詞
      ['achieve','達成する','ətʃíːv'],
      ['remain','依然として〜だ','riméin'],
      ['identify','特定する','aidéntifai'],
      ['indicate','示す','índikeit'],
      ['maintain','維持する','meintéin'],
      ['obtain','得る','əbtéin'],
      ['promote','促進する','prəmóut'],
      ['prevent','防ぐ','privént'],
      ['recognize','認識する','rékəgnaiz'],
      ['relate','関連する','riléit'],
      ['respond','反応する','rispɑ́nd'],
      ['reveal','明かす','rivíːl'],
      ['seek','求める','síːk'],
      ['solve','解決する','sɑ́lv'],
      ['tend','〜する傾向がある','ténd'],
      ['represent','代表する','reprəzént'],
      ['reflect','反映する','riflékt'],
      ['focus','焦点を当てる','fóukəs'],
      ['generate','生み出す','dʒénəreit'],
      ['evaluate','評価する','ivǽljueit'],
      ['realize','気づく','ríːəlaiz'],
      ['assume','想定する','əsjúːm'],
      ['determine','決定する','ditə́ːrmin'],
      ['establish','設立する','istǽbliʃ'],
      ['claim','主張する','kléim'],
      ['concern','心配させる','kənsə́ːrn'],
      ['extend','拡大する','iksténd'],
      ['observe','観察する','əbzə́ːrv'],
      ['serve','役立つ','sə́ːrv'],
      ['involve','関係させる','invɑ́lv'],
      ['encourage','励ます','inkʌ́ridʒ'],
      ['enable','可能にする','inéibl'],
      ['connect','接続する','kənékt'],
      ['ensure','確保する','inʃúər'],
      ['depend','依存する','dipénd'],
      ['conduct','行う','kɑ́ndʌkt'],
      ['complete','完成させる','kəmplíːt'],
      ['combine','組み合わせる','kəmbáin'],
      ['supply','供給する','səplái'],
      ['measure','測る','méʒər'],
      ['select','選択する','silékt'],
      ['control','制御する','kəntróul'],
      ['perform','実行する','pərfɔ́ːrm'],
      ['share','共有する','ʃέər'],
      ['prepare','準備する','pripέər'],
      ['compare','比較する','kəmpέər'],
      ['avoid','避ける','əvɔ́id'],
      ['introduce','導入する','intrədjúːs'],
      ['rely','依存する','rilái'],
      ['transfer','移転する','trǽnsfər'],
      ['investigate','調査する','invéstigeit'],
      ['argue','主張する','ɑ́ːrgjuː'],
      ['attract','引きつける','ətrækt'],
      ['confirm','確認する','kənfə́ːrm'],
      ['contain','含む','kəntéin'],
      ['cope','対処する','kóup'],
      ['damage','損傷する','dǽmidʒ'],
      ['define','定義する','difáin'],
      ['deny','否定する','dinái'],
      ['design','設計する','dizáin'],
      ['distribute','分配する','distribjúːt'],
      ['divide','分割する','diváid'],
      ['employ','雇用する','implɔ́i'],
      ['engage','従事する','ingéidʒ'],
      ['estimate','推定する','éstimeit'],
      ['examine','調べる','igzǽmin'],
      ['exchange','交換する','ikstʃéindʒ'],
      ['expand','拡大する','ikspǽnd'],
      ['export','輸出する','ekspɔ́ːrt'],
      ['force','強制する','fɔ́ːrs'],
      ['handle','扱う','hǽndl'],
      ['ignore','無視する','ignɔ́ːr'],
      ['import','輸入する','impɔ́ːrt'],
      ['inform','知らせる','infɔ́ːrm'],
      ['inspire','鼓舞する','inspáiər'],
      ['intend','意図する','inténd'],
      ['invest','投資する','invést'],
      ['lack','欠く','lǽk'],
      ['limit','制限する','límit'],
      ['link','結ぶ','líŋk'],
      ['manage','管理する','mǽnidʒ'],
      ['mention','言及する','ménʃən'],
      ['monitor','監視する','mɑ́nitər'],
      ['notice','気づく','nóutis'],
      ['participate','参加する','pɑːrtísəpeit'],
      ['predict','予測する','pridíkt'],
      ['prove','証明する','prúːv'],
      ['publish','出版する','pʌ́bliʃ'],
      ['record','記録する','rékərd'],
      ['refer','言及する','rifə́ːr'],
      ['refuse','断る','rifjúːz'],
      ['release','公開する','rilíːs'],
      ['remind','思い出させる','rimáind'],
      ['remove','取り除く','rimúːv'],
      ['report','報告する','ripɔ́ːrt'],
      ['review','見直す','rivjúː'],
      ['search','探す','sə́ːrtʃ'],
      ['sign','署名する','sáin'],
      ['state','述べる','stéit'],
      ['struggle','苦闘する','strʌ́gl'],
      ['update','更新する','ʌpdéit'],
      ['warn','警告する','wɔ́ːrn'],
      ['analyze','分析する','ǽnəlaiz'],
      ['adapt','適応する','ədǽpt'],
      ['address','取り組む','ədrés'],
      ['alter','変える','ɔ́ltər'],
      ['apply','適用する','əplái'],
      ['approach','近づく','əpróutʃ'],
      ['build','構築する','bíld'],
      ['collaborate','協力する','kəlǽbəreit'],
      ['communicate','伝える','kəmjúːnikeit'],
      ['compete','競争する','kəmpíːt'],
      ['construct','構築する','kənstrʌ́kt'],
      ['consume','消費する','kənsjúːm'],
      ['convince','説得する','kənvíns'],
      ['decline','減少する','dikláin'],
      ['demonstrate','実証する','démənstreit'],
      ['detect','検出する','ditékt'],
      ['eliminate','排除する','ilímineit'],
      ['emphasize','強調する','émfəsaiz'],
      ['enhance','強化する','inhǽns'],
      ['evolve','進化する','ivɑ́lv'],
      ['exceed','超える','iksíːd'],
      ['expose','さらす','ikspóuz'],
      ['implement','実施する','ímplimènt'],
      ['imply','示唆する','implái'],
      ['integrate','統合する','íntəgreit'],
      ['interpret','解釈する','intə́ːrprit'],
      ['justify','正当化する','dʒʌ́stifai'],
      ['modify','修正する','mɑ́difai'],
      ['overcome','克服する','òuvərkʌ́m'],
      ['perceive','知覚する','pərsíːv'],
      ['propose','提案する','prəpóuz'],
      ['pursue','追求する','pərsjúː'],
      ['reject','拒否する','ridʒékt'],
      ['transform','変革する','trænsfɔ́ːrm'],
      // 名詞
      ['ability','能力','əbíləti'],
      ['approach','アプローチ','əpróutʃ'],
      ['aspect','側面','ǽspekt'],
      ['attitude','態度','ǽtitjuːd'],
      ['behavior','行動','bihéivjər'],
      ['benefit','利益','bénəfit'],
      ['concept','概念','kɑ́nsept'],
      ['concern','懸念','kənsə́ːrn'],
      ['condition','条件、状態','kəndíʃən'],
      ['conflict','対立','kɑ́nflikt'],
      ['context','文脈','kɑ́ntekst'],
      ['culture','文化','kʌ́ltʃər'],
      ['decade','10年','dékeid'],
      ['decision','決定','disíʒən'],
      ['demand','需要','dimǽnd'],
      ['development','発展','divéləpmənt'],
      ['economy','経済','ikɑ́nəmi'],
      ['education','教育','èdʒukéiʃən'],
      ['element','要素','éləmənt'],
      ['energy','エネルギー','énərdʒi'],
      ['evidence','証拠','évədəns'],
      ['factor','要因','fǽktər'],
      ['feature','特徴','fíːtʃər'],
      ['function','機能','fʌ́ŋkʃən'],
      ['goal','目標','góul'],
      ['government','政府','gʌ́vərnmənt'],
      ['growth','成長','gróuθ'],
      ['impact','影響','ímpækt'],
      ['individual','個人','ìndivídʒuəl'],
      ['influence','影響','ínfluəns'],
      ['method','方法','méθəd'],
      ['model','モデル','mɑ́dl'],
      ['movement','運動','múːvmənt'],
      ['nation','国家','néiʃən'],
      ['network','ネットワーク','nétwə̀ːrk'],
      ['organization','組織','ɔ̀ːrgənəzéiʃən'],
      ['pattern','パターン','pǽtərn'],
      ['policy','政策','pɑ́ləsi'],
      ['population','人口','pɑ̀pjuléiʃən'],
      ['potential','可能性','pouténʃəl'],
      ['practice','実践','prǽktis'],
      ['purpose','目的','pə́ːrpəs'],
      ['quality','質','kwɑ́ləti'],
      ['range','範囲','réindʒ'],
      ['relationship','関係','riléiʃənʃìp'],
      ['resource','資源','ríːsɔːrs'],
      ['responsibility','責任','rispɑ̀nsəbíləti'],
      ['risk','リスク','rísk'],
      ['role','役割','róul'],
      ['scale','規模','skéil'],
      ['situation','状況','sìtʃuéiʃən'],
      ['skill','技術','skíl'],
      ['solution','解決策','səlúːʃən'],
      ['source','源','sɔ́ːrs'],
      ['standard','標準','stǽndərd'],
      ['strategy','戦略','strǽtədʒi'],
      ['structure','構造','strʌ́ktʃər'],
      ['study','研究','stʌ́di'],
      ['technology','技術','teknɑ́lədʒi'],
      ['term','用語、期間','tə́ːrm'],
      ['trend','傾向','trénd'],
      ['value','価値','vǽljuː'],
      ['community','地域社会','kəmjúːnəti'],
      ['diversity','多様性','daivə́ːrsəti'],
      ['institution','機関','ìnstətjúːʃən'],
      ['capacity','能力','kəpǽsəti'],
      // 形容詞
      ['significant','重要な','signífikənt'],
      ['available','利用可能な','əvéiləbl'],
      ['specific','特定の','spəsífik'],
      ['major','主要な','méidʒər'],
      ['effective','効果的な','iféktiv'],
      ['particular','特定の','pərtíkjulər'],
      ['primary','主要な','práiməri'],
      ['positive','前向きな','pɑ́zətiv'],
      ['global','世界的な','glóubəl'],
      ['essential','不可欠な','isénʃəl'],
      ['traditional','伝統的な','trədíʃənəl'],
      ['economic','経済的な','ìːkənɑ́mik'],
      ['national','国家の','næʃənəl'],
      ['cultural','文化的な','kʌ́ltʃərəl'],
      ['political','政治的な','pəlítikəl'],
      ['environmental','環境の','invàiərənméntl'],
      ['unique','独自の','juːníːk'],
      ['relevant','関連した','réləvənt'],
      ['appropriate','適切な','əpróupriit'],
      ['aware','気づいている','əwέər'],
      ['complex','複雑な','kɑ́mpleks'],
      ['efficient','効率的な','ifíʃənt'],
      ['crucial','極めて重要な','krúːʃəl'],
      ['academic','学術的な','ækədémik'],
      ['additional','追加の','ədíʃənəl'],
      ['alternative','代替の','ɔːltə́ːrnətiv'],
      ['annual','年間の','ǽnjuəl'],
      ['basic','基本的な','béisik'],
      ['capable','〜できる','képəbl'],
      ['certain','確かな','sə́ːrtn'],
      ['competitive','競争的な','kəmpétətiv'],
      ['contemporary','現代の','kəntémpərèri'],
      ['creative','創造的な','kriéitiv'],
      ['direct','直接の','dirékt'],
      ['dominant','優勢な','dɑ́minənt'],
      ['dynamic','活動的な','dainǽmik'],
      ['flexible','柔軟な','fléksəbl'],
      ['formal','正式の','fɔ́ːrməl'],
      ['frequent','頻繁な','fríːkwənt'],
      ['historical','歴史的な','histɔ́ːrikəl'],
      ['independent','独立した','ìndipéndənt'],
      ['industrial','産業の','indʌ́striəl'],
      ['initial','最初の','iníʃəl'],
      ['intense','激しい','inténs'],
      ['modern','現代の','mɑ́dərn'],
      ['moral','道徳的な','mɔ́ːrəl'],
      ['multiple','複数の','mʌ́ltəpl'],
      ['mutual','相互の','mjúːtʃuəl'],
      ['negative','否定的な','négətiv'],
      ['neutral','中立の','njúːtrəl'],
      ['official','公式の','əfíʃəl'],
      ['ordinary','普通の','ɔ́ːrdinèri'],
      ['original','独自の','ərídʒənəl'],
      ['overall','全体的な','óuvərɔ̀ːl'],
      ['permanent','永続的な','pə́ːrmənənt'],
      ['personal','個人的な','pə́ːrsənəl'],
      ['practical','実用的な','prǽktikəl'],
      ['professional','専門的な','prəféʃənəl'],
      ['rational','合理的な','rǽʃənəl'],
      ['realistic','現実的な','rìːəlístik'],
      ['regional','地域の','ríːdʒənəl'],
      ['regular','定期的な','régjulər'],
      ['relative','相対的な','rélətiv'],
      ['reliable','信頼できる','riláiəbl'],
      ['responsible','責任ある','rispɑ́nsəbl'],
      ['scientific','科学的な','sàiəntífik'],
      ['severe','深刻な','sivíər'],
      ['stable','安定した','stéibl'],
      ['strict','厳しい','stríkt'],
      ['substantial','実質的な','səbstǽnʃəl'],
      ['sustainable','持続可能な','səstéinəbl'],
      ['theoretical','理論的な','θìːərétikəl'],
      ['urban','都市の','ə́ːrbən'],
      ['widespread','広まった','wáidspred'],
      // 副詞
      ['therefore','したがって','ðέərfɔ̀ːr'],
      ['moreover','その上','mɔːróuvər'],
      ['nevertheless','それでも','nèvərðəlés'],
      ['consequently','結果として','kɑ́nsikwəntli'],
      ['furthermore','さらに','fə́ːrðərmɔ̀ːr'],
      ['whereas','一方で','hwεərǽz'],
      ['increasingly','ますます','inkríːsiŋli'],
      ['significantly','著しく','signífikəntli'],
      ['relatively','比較的に','rélətivli'],
      ['particularly','特に','pərtíkjuləli'],
      ['essentially','本質的に','isénʃəli'],
      ['ultimately','最終的に','ʌ́ltimətli'],
      ['accordingly','それに応じて','əkɔ́ːrdiŋli'],
      ['approximately','おおよそ','əprɑ́ksimətli'],
      ['consistently','一貫して','kənsístəntli'],
      ['effectively','効果的に','iféktivli'],
      ['extensively','広く','iksténsivli'],
      ['meanwhile','一方で','míːnwàil'],
      ['nonetheless','それでもなお','nʌ̀nðəlés'],
      ['otherwise','さもなければ','ʌ́ðərwàiz'],
      ['subsequently','その後','sʌ́bsikwəntli'],
      ['typically','典型的に','típikəli'],
    ]
  },

  // ════════════════════════════════
  //  上級編  難関大・東大京大レベル
  // ════════════════════════════════
  {
    id: 'exam-advanced',
    name: '難関大 上級',
    icon: 'award',
    color: '#4a0010',
    description: '東大・京大・早慶レベルの高難度単語。論述・読解の核心語彙。',
    words: [
      // 動詞
      ['abolish','廃止する','əbɑ́liʃ'],
      ['alleviate','和らげる','əlíːvieit'],
      ['amplify','増幅する','ǽmplifai'],
      ['articulate','明確に述べる','ɑːrtíkjuleit'],
      ['aspire','熱望する','əspáiər'],
      ['consolidate','統合する','kənsɑ́lideit'],
      ['contradict','矛盾する','kɑ̀ntrədíkt'],
      ['cultivate','育てる','kʌ́ltiveit'],
      ['deduce','演繹する','didjúːs'],
      ['deplete','使い果たす','diplíːt'],
      ['designate','指定する','dézigneit'],
      ['deteriorate','悪化する','ditíəriəreit'],
      ['differentiate','区別する','dìfəréntʃieit'],
      ['disrupt','混乱させる','disrʌ́pt'],
      ['diversify','多様化する','divə́ːrsifai'],
      ['empower','権限を与える','impáuər'],
      ['enforce','施行する','infɔ́ːrs'],
      ['eradicate','根絶する','irǽdikèit'],
      ['exacerbate','悪化させる','igzǽsərbeit'],
      ['facilitate','促進する','fəsíliteit'],
      ['formulate','策定する','fɔ́ːrmjuleit'],
      ['hamper','妨げる','hǽmpər'],
      ['incorporate','取り入れる','inkɔ́ːrpəreit'],
      ['infer','推論する','infə́ːr'],
      ['initiate','開始する','iníʃieit'],
      ['innovate','革新する','ínəveit'],
      ['mediate','仲介する','míːdieit'],
      ['mitigate','軽減する','mítigeit'],
      ['mobilize','動員する','móubəlaiz'],
      ['neutralize','中和する','njúːtrəlaiz'],
      ['optimize','最適化する','ɑ́ptəmaiz'],
      ['oversee','監督する','òuvərsíː'],
      ['perpetuate','永続させる','pərpétʃueit'],
      ['postulate','仮定する','pɑ́stʃuleit'],
      ['prioritize','優先する','praiɔ́rətaiz'],
      ['rationalize','合理化する','rǽʃənəlaiz'],
      ['rectify','修正する','réktifai'],
      ['reinforce','強化する','rìːinfɔ́ːrs'],
      ['render','〜にする','réndər'],
      ['scrutinize','詳しく調べる','skrúːtənaiz'],
      ['simulate','シミュレートする','símjuleit'],
      ['standardize','標準化する','stǽndərdaiz'],
      ['streamline','合理化する','stríːmlàin'],
      ['synthesize','合成する','sínθəsaiz'],
      ['transcend','超越する','trænsénd'],
      ['undermine','弱体化させる','ʌ̀ndərmáin'],
      ['validate','証明する','vǽlideit'],
      ['withstand','耐える','wiθstǽnd'],
      ['abdicate','放棄する','ǽbdikèit'],
      ['accommodate','対応する','əkɑ́mədeit'],
      ['aggravate','悪化させる','ǽgrəveit'],
      ['coerce','強制する','kouə́ːrs'],
      ['compel','強制する','kəmpél'],
      ['confiscate','没収する','kɑ́nfiskèit'],
      ['corroborate','裏付ける','kərɑ́bərèit'],
      ['curtail','削減する','kəːrtéil'],
      ['deliberate','熟慮する','dilíbərèit'],
      ['denounce','非難する','dináuns'],
      ['depict','描写する','dipíkt'],
      ['derive','〜に由来する','diráiv'],
      ['disseminate','広める','diséminèit'],
      ['dominate','支配する','dɑ́mineit'],
      ['elucidate','明確にする','ilúːsidèit'],
      ['endorse','支持する','indɔ́ːrs'],
      ['envisage','想像する','invízidʒ'],
      ['exploit','活用する','éksplɔit'],
      ['extrapolate','推定する','ikstrǽpəleit'],
      ['foster','促進する','fɑ́stər'],
      ['impede','妨げる','impíːd'],
      ['invoke','援用する','invóuk'],
      ['negate','否定する','nigéit'],
      ['oscillate','振動する','ɑ́silèit'],
      ['permeate','浸透する','pə́ːrmieit'],
      ['precipitate','促進する','prisípitèit'],
      ['presuppose','前提とする','prìːsəpóuz'],
      ['prevail','普及する','privéil'],
      ['proliferate','急増する','prəlífərèit'],
      ['reconcile','和解させる','rékənsàil'],
      ['repudiate','拒絶する','ripjúːdieit'],
      ['subsist','生存する','səbsíst'],
      ['sustain','維持する','səstéin'],
      ['transcribe','書き写す','trænskráib'],
      ['vindicate','正当性を証明する','víndikèit'],
      // 名詞
      ['accountability','説明責任','əkàuntəbíləti'],
      ['ambiguity','曖昧さ','æ̀mbigjúːəti'],
      ['autonomy','自律性','ɔːtɑ́nəmi'],
      ['bureaucracy','官僚制','bjuərɑ́krəsi'],
      ['catalyst','促進要因','kǽtəlist'],
      ['coherence','一貫性','kouhíərəns'],
      ['complexity','複雑さ','kəmpléksiti'],
      ['consensus','合意','kənsénsis'],
      ['credibility','信頼性','krèdəbíləti'],
      ['curriculum','カリキュラム','kəríkjuləm'],
      ['democracy','民主主義','dimɑ́krəsi'],
      ['disparity','格差','dispǽrəti'],
      ['ecosystem','生態系','íːkousìstəm'],
      ['empiricism','経験主義','impírisìzm'],
      ['empathy','共感','émpəθi'],
      ['equilibrium','均衡','ìːkwilíbriəm'],
      ['expertise','専門知識','èkspərtíːz'],
      ['extinction','絶滅','ikstíŋkʃən'],
      ['globalization','グローバル化','glòubələzéiʃən'],
      ['governance','統治','gʌ́vərnəns'],
      ['hegemony','覇権','hidʒéməni'],
      ['hierarchy','階層','háiərɑ̀ːrki'],
      ['hypothesis','仮説','haipɑ́θəsis'],
      ['ideology','イデオロギー','àidiɑ́lədʒi'],
      ['implementation','実施','ìmpliménteiʃən'],
      ['incentive','動機','inséntiv'],
      ['inequality','不平等','ìnikwɑ́ləti'],
      ['infrastructure','インフラ','ínfrəstrʌ̀ktʃər'],
      ['innovation','革新','ìnəvéiʃən'],
      ['integrity','誠実さ','intégriti'],
      ['interdependence','相互依存','ìntərdipéndəns'],
      ['intuition','直感','ìntjuíʃən'],
      ['legitimacy','正当性','lidʒítəməsi'],
      ['literacy','読み書き能力','lítərəsi'],
      ['magnitude','規模','mǽgnitjùːd'],
      ['manifestation','表れ','mæ̀nifestéiʃən'],
      ['mechanism','仕組み','mékənìzəm'],
      ['methodology','方法論','mèθədɑ́lədʒi'],
      ['morality','道徳性','mərǽləti'],
      ['nationalism','ナショナリズム','næʃənəlìzm'],
      ['objectivity','客観性','ɑ̀bdʒektiviti'],
      ['paradox','逆説','pǽrədɑ̀ks'],
      ['paradigm','パラダイム','pǽrədàim'],
      ['persistence','持続性','pərsístəns'],
      ['phenomenon','現象','finɑ́minòn'],
      ['pragmatism','実用主義','prǽgmətìzm'],
      ['productivity','生産性','prɑ̀dʌktívəti'],
      ['rationality','合理性','rǽʃənǽləti'],
      ['recession','景気後退','risépʃən'],
      ['resilience','回復力','rizíliəns'],
      ['rhetoric','修辞、言い回し','rétərik'],
      ['sovereignty','主権','sɑ́vrənti'],
      ['spectrum','範囲','spéktrəm'],
      ['stereotype','固定観念','stériətàip'],
      ['subsidy','補助金','sʌ́bsədi'],
      ['surplus','余剰','sə́ːrpləs'],
      ['sustainability','持続可能性','səstèinəbíləti'],
      ['synthesis','合成','sínθəsis'],
      ['tenet','信条、原則','ténet'],
      ['transparency','透明性','trǽnspærənsi'],
      ['ambivalence','両義性','æmbívələns'],
      ['arbitration','仲裁','ɑ̀ːrbitréiʃən'],
      ['complacency','現状満足','kəmpléisənsi'],
      ['conjecture','推測','kəndʒéktʃər'],
      ['correlation','相関関係','kɔ̀ːrəléiʃən'],
      ['delineation','描写、区画','dilìniéiʃən'],
      ['dichotomy','二分法','daikɑ́təmi'],
      ['dissent','異論、不同意','disént'],
      ['dominance','支配','dɑ́minəns'],
      ['entropy','エントロピー','éntrəpi'],
      ['fallacy','誤謬','fǽləsi'],
      ['fatalism','宿命論','féitəlìzm'],
      ['fidelity','忠実さ','fidéləti'],
      ['fragmentation','断片化','frægmèntéiʃən'],
      ['imperialism','帝国主義','impíəriəlìzm'],
      ['indoctrination','思想注入','indɑ̀ktrinéiʃən'],
      ['juxtaposition','並置','dʒʌ̀kstəpəzíʃən'],
      ['leverage','影響力','lévəridʒ'],
      ['marginalization','周縁化','mɑ̀ːrdʒinəlizéiʃən'],
      ['nihilism','ニヒリズム','náiilìzm'],
      ['nuance','ニュアンス','njúːɑːns'],
      ['ostracism','追放','ɑ́strəsìzm'],
      ['philanthropy','慈善活動','filǽnθrəpi'],
      ['polarization','二極化','pòulərizéiʃən'],
      ['pragmatism','実用主義','prǽgmətìzm'],
      ['precedent','前例','présidənt'],
      ['propaganda','プロパガンダ','prɑ̀pəgǽndə'],
      ['relativism','相対主義','rélətivìzm'],
      ['repercussion','反響、影響','rìːpərkʌ́ʃən'],
      ['schism','分裂','skízm'],
      ['secularism','世俗主義','sékjulərizm'],
      ['skepticism','懐疑主義','sképtisìzm'],
      ['solidarity','連帯','sɑ̀lədǽrəti'],
      ['stagnation','停滞','stægnéiʃən'],
      ['stigma','汚名','stígmə'],
      ['totalitarianism','全体主義','toutæ̀litέəriənìzm'],
      ['utilitarianism','功利主義','juːtìlitέəriənìzm'],
      ['vulnerability','脆弱性','vʌ̀lnərəbíləti'],
      // 形容詞
      ['abstract','抽象的な','ǽbstrækt'],
      ['adverse','不利な','ǽdvəːrs'],
      ['ambiguous','曖昧な','æmbígjuəs'],
      ['analogous','類似した','ənǽləgəs'],
      ['arbitrary','恣意的な','ɑ́ːrbitrèri'],
      ['autonomous','自律的な','ɔːtɑ́nəməs'],
      ['chronic','慢性的な','krɑ́nik'],
      ['coherent','一貫した','kouhíərənt'],
      ['cumulative','累積的な','kjúːmjulətiv'],
      ['decisive','決定的な','disáisiv'],
      ['devastating','壊滅的な','dévəstèitiŋ'],
      ['empirical','実証的な','impírikəl'],
      ['feasible','実行可能な','fíːzəbl'],
      ['fundamental','根本的な','fʌ̀ndəméntl'],
      ['ideological','イデオロギー的な','àidiəlɑ́dʒikəl'],
      ['implicit','暗黙の','implísit'],
      ['inclusive','包括的な','inklúːsiv'],
      ['inherent','固有の','inhíərənt'],
      ['intrinsic','本質的な','intrínzik'],
      ['irreversible','不可逆的な','irrivə́ːrsəbl'],
      ['legitimate','正当な','lidʒítimit'],
      ['negligible','無視できる','néglidʒəbl'],
      ['obsolete','時代遅れの','ɑ́bsəlìːt'],
      ['optimal','最適な','ɑ́ptimol'],
      ['pervasive','広く行き渡る','pərvéisiv'],
      ['plausible','もっともらしい','plɔ́ːzəbl'],
      ['predominant','優勢な','pridɑ́minənt'],
      ['preliminary','予備的な','priléminèri'],
      ['profound','深遠な','prəfáund'],
      ['redundant','余剰な','ridʌ́ndənt'],
      ['rigid','硬直した','rídʒid'],
      ['robust','強固な','roubʌ́st'],
      ['sequential','連続的な','sikwénʃəl'],
      ['skeptical','懐疑的な','sképtikəl'],
      ['spontaneous','自発的な','spɑntéiniəs'],
      ['subtle','微妙な','sʌ́tl'],
      ['tentative','暫定的な','téntətiv'],
      ['trivial','ささいな','tríviəl'],
      ['unanimous','満場一致の','juːnǽniməs'],
      ['unprecedented','前例のない','ʌnprésidèntid'],
      ['vague','曖昧な','véig'],
      ['viable','実行可能な','váiəbl'],
      ['volatile','不安定な','vɑ́lətl'],
      ['vulnerable','脆弱な','vʌ́lnərəbl'],
      ['contentious','議論を呼ぶ','kənténʃəs'],
      ['contingent','偶発的な','kəntíndʒənt'],
      ['counterproductive','逆効果の','kàuntərprədʌ́ktiv'],
      ['detrimental','有害な','dètrəméntl'],
      ['dichotomous','二分法的な','daikɑ́təməs'],
      ['disparate','異質な','díspərət'],
      ['ephemeral','はかない','ifémərel'],
      ['exhaustive','徹底的な','igzɔ́ːstiv'],
      ['expedient','便宜的な','ikspíːdiənt'],
      ['explicit','明示的な','iksplísit'],
      ['formidable','恐ろしいほどの','fɔ́ːrmidəbl'],
      ['hypothetical','仮定の','hàipəθétikəl'],
      ['immutable','不変の','imjúːtəbl'],
      ['impervious','影響されない','impə́ːrviəs'],
      ['incessant','絶え間ない','insésənt'],
      ['incongruent','不一致の','inkɑ́ŋgruənt'],
      ['indigenous','固有の','indídʒənəs'],
      ['indispensable','不可欠な','ìndispénsəbl'],
      ['inexorable','止められない','inéksorəbl'],
      ['insidious','陰険な','insídiəs'],
      ['intractable','手に負えない','intrǽktəbl'],
      ['marginal','わずかな','mɑ́ːrdʒinəl'],
      ['meticulous','細心の','mitíkjuləs'],
      ['nuanced','微妙な','njúːɑːnst'],
      ['obsolete','時代遅れの','ɑ́bsəlìːt'],
      ['omnipresent','遍在する','ɑ̀mniprézənt'],
      ['paradoxical','逆説的な','pæ̀rədɑ́ksikəl'],
      ['peripheral','周辺の','pəríferəl'],
      ['pragmatic','実用的な','præmǽtik'],
      ['precarious','不安定な','prikέəriəs'],
      ['propitious','好都合な','prəpíʃəs'],
      ['provincial','地方の、偏狭な','prəvínʃəl'],
      ['reciprocal','相互の','risíprəkl'],
      ['reductive','還元的な','ridʌ́ktiv'],
      ['salient','顕著な','séiliənt'],
      ['superfluous','余分な','supə́ːrfluəs'],
      ['tenuous','薄い、弱い','ténjuəs'],
      ['transient','一時的な','trǽnʃənt'],
      ['ubiquitous','遍在する','juːbíkwitəs'],
      ['unequivocal','明確な','ʌ̀nikwívəkəl'],
      ['unprecedented','前例のない','ʌnprésidèntid'],
      ['unwarranted','根拠のない','ʌnwɔ́ːrəntid'],
    ]
  }

];

// ════════════════════════════════
//  TOEIC 目標得点別単語リスト
//  TOEICの出題パターンを分析した独自編集リスト
// ════════════════════════════════
const TOEIC_LISTS = [

  // ────────────────────────────
  //  TOEIC 500点目標
  // ────────────────────────────
  {
    id: 'toeic-500',
    name: 'TOEIC 500点目標',
    icon: 'target',
    color: '#14532d',
    description: 'TOEIC 500点突破に必要なビジネス基礎単語。日常業務・メールの頻出語。',
    words: [
      // ビジネス基本動詞
      ['schedule','予定する；予定','skédʒuːl'],
      ['confirm','確認する','kənfə́ːrm'],
      ['contact','連絡する；連絡先','kɑ́ntækt'],
      ['order','注文する；順序','ɔ́ːrdər'],
      ['deliver','届ける','dilívər'],
      ['receive','受け取る','risíːv'],
      ['send','送る','sénd'],
      ['attend','出席する','əténd'],
      ['cancel','キャンセルする','kǽnsəl'],
      ['postpone','延期する','poustpóun'],
      ['arrange','手配する','əréindʒ'],
      ['reserve','予約する','rizə́ːrv'],
      ['book','予約する；本','búk'],
      ['apply','申し込む','əplái'],
      ['hire','雇う','háiər'],
      ['promote','昇進させる','prəmóut'],
      ['retire','退職する','ritáiər'],
      ['resign','辞任する','rizáin'],
      ['announce','発表する','ənáuns'],
      ['report','報告する','ripɔ́ːrt'],
      ['check','確認する','tʃék'],
      ['review','見直す；評価','rivjúː'],
      ['submit','提出する','səbmít'],
      ['approve','承認する','əprúːv'],
      ['sign','署名する','sáin'],
      ['update','更新する','ʌpdéit'],
      ['discuss','議論する','diskʌ́s'],
      ['meet','会う；満たす','míːt'],
      ['follow up','後追いする',''],
      ['reach','連絡を取る','ríːtʃ'],
      ['assist','助ける','əsíst'],
      ['handle','対応する','hǽndl'],
      ['complete','完了する','kəmplíːt'],
      ['prepare','準備する','pripέər'],
      ['present','発表する；提出する','prizént'],
      ['fill out','記入する',''],
      ['look into','調べる',''],
      ['take care of','〜を処理する',''],
      ['deal with','〜に対処する',''],
      ['get back to','〜に折り返す',''],
      // ビジネス名詞
      ['meeting','会議','míːtiŋ'],
      ['appointment','予約；約束','əpɔ́intmənt'],
      ['deadline','締め切り','dédlàin'],
      ['schedule','スケジュール','skédʒuːl'],
      ['agenda','議題','ədʒéndə'],
      ['minutes','議事録','mínits'],
      ['report','報告書','ripɔ́ːrt'],
      ['document','文書','dɑ́kjumənt'],
      ['form','書類、フォーム','fɔːrm'],
      ['invoice','請求書','ínvɔis'],
      ['receipt','領収書','risíːt'],
      ['contract','契約書','kɑ́ntrækt'],
      ['budget','予算','bʌ́dʒit'],
      ['expense','経費','ikspéns'],
      ['salary','給与','sǽləri'],
      ['bonus','ボーナス','bóunəs'],
      ['benefit','福利厚生；利益','bénəfit'],
      ['department','部署','dipɑ́ːrtmənt'],
      ['branch','支社','brǽntʃ'],
      ['headquarters','本社','hédkwɔ̀ːrtərz'],
      ['staff','スタッフ','stǽf'],
      ['employee','従業員','implɔ́iiː'],
      ['employer','雇用主','implɔ́iər'],
      ['manager','マネージャー','mǽnidʒər'],
      ['supervisor','上司','súːpərvàizər'],
      ['colleague','同僚','kɑ́liːg'],
      ['client','クライアント','kláiənt'],
      ['customer','顧客','kʌ́stəmər'],
      ['supplier','仕入れ先','səpláiər'],
      ['vendor','販売業者','véndər'],
      ['order','注文','ɔ́ːrdər'],
      ['shipment','出荷','ʃípmənt'],
      ['delivery','配達','dilívəri'],
      ['package','荷物；パッケージ','pǽkidʒ'],
      ['product','製品','prɑ́dʌkt'],
      ['service','サービス','sə́ːrvis'],
      ['price','価格','práis'],
      ['discount','割引','dískàunt'],
      ['offer','申し出；提供','ɑ́fər'],
      ['proposal','提案書','prəpóuzəl'],
      ['project','プロジェクト','prɑ́dʒekt'],
      ['task','課題','tǽsk'],
      ['deadline','期限','dédlàin'],
      ['progress','進捗','prɑ́gres'],
      ['result','結果','rizʌ́lt'],
      ['goal','目標','góul'],
      ['target','目標','tɑ́ːrgit'],
      ['plan','計画','plǽn'],
      ['policy','方針','pɑ́ləsi'],
      ['procedure','手順','prəsíːdʒər'],
      ['equipment','設備','ikwípmənt'],
      ['facility','施設','fəsíləti'],
      ['office','オフィス','ɔ́fis'],
      ['conference room','会議室',''],
      ['telephone','電話','téləfòun'],
      ['email','メール','íːmèil'],
      ['fax','ファックス','fǽks'],
      ['copy','コピー','kɑ́pi'],
      // 形容詞・副詞
      ['available','利用可能な','əvéiləbl'],
      ['busy','忙しい','bízi'],
      ['urgent','緊急の','ə́ːrdʒənt'],
      ['important','重要な','impɔ́ːrtənt'],
      ['necessary','必要な','nésəsèri'],
      ['responsible','責任ある','rispɑ́nsəbl'],
      ['efficient','効率的な','ifíʃənt'],
      ['professional','専門的な','prəféʃənəl'],
      ['successful','成功した','səksésful'],
      ['on time','時間通りに',''],
      ['ahead of schedule','予定より早く',''],
      ['behind schedule','予定より遅れて',''],
      ['as soon as possible','できる限り早く',''],
      ['at your earliest convenience','ご都合のよいときに',''],
      ['please find attached','添付をご確認ください',''],
      ['regarding','〜について',''],
      ['with regard to','〜に関して',''],
      ['in addition','さらに',''],
    ]
  },

  // ────────────────────────────
  //  TOEIC 700点目標
  // ────────────────────────────
  {
    id: 'toeic-700',
    name: 'TOEIC 700点目標',
    icon: 'trophy',
    color: '#1e3a5f',
    description: 'TOEIC 700点突破に必要な中級ビジネス語彙。会議・交渉・マーケティングの頻出語。',
    words: [
      // 動詞
      ['negotiate','交渉する','nigóuʃieit'],
      ['implement','実施する','ímplimènt'],
      ['coordinate','調整する','kouɔ́ːrdəneit'],
      ['allocate','割り当てる','ǽləkeit'],
      ['estimate','見積もる','éstimeit'],
      ['forecast','予測する','fɔ́ːrkæ̀st'],
      ['outsource','外注する','áutsɔ̀ːrs'],
      ['streamline','合理化する','stríːmlàin'],
      ['launch','発売する；始める','lɔ́ːntʃ'],
      ['expand','拡大する','ikspǽnd'],
      ['acquire','買収する','əkwáiər'],
      ['merge','合併する','mə́ːrdʒ'],
      ['collaborate','協力する','kəlǽbəreit'],
      ['delegate','委任する','déligeit'],
      ['monitor','監視する','mɑ́nitər'],
      ['evaluate','評価する','ivǽljueit'],
      ['prioritize','優先する','praiɔ́rətaiz'],
      ['maximize','最大化する','mǽksəmaiz'],
      ['minimize','最小化する','mínəmaiz'],
      ['optimize','最適化する','ɑ́ptəmaiz'],
      ['restructure','再編する','rìːstrʌ́ktʃər'],
      ['downsize','縮小する','dáunsàiz'],
      ['recruit','採用する','rikrúːt'],
      ['train','研修する','tréin'],
      ['motivate','動機づける','móutiveit'],
      ['compensate','補償する','kɑ́mpənseit'],
      ['reimburse','払い戻す','rìːimbə́ːrs'],
      ['invoice','請求書を送る','ínvɔis'],
      ['audit','監査する','ɔ́ːdit'],
      ['invest','投資する','invést'],
      ['fund','資金提供する','fʌ́nd'],
      ['secure','確保する','sikjúər'],
      ['retain','保持する','ritéin'],
      ['maintain','維持する','meintéin'],
      ['enhance','強化する','inhǽns'],
      ['improve','改善する','imprúːv'],
      ['address','取り組む','ədrés'],
      ['resolve','解決する','rizɑ́lv'],
      ['comply with','〜に従う',''],
      ['adhere to','〜を守る',''],
      ['account for','〜を占める',''],
      ['bring about','引き起こす',''],
      ['carry out','実行する',''],
      ['come up with','考え出す',''],
      ['draw up','作成する',''],
      ['roll out','展開する',''],
      ['set up','設立する',''],
      ['take on','引き受ける',''],
      ['turn down','断る',''],
      ['work out','解決する',''],
      // 名詞
      ['revenue','収益','révənjuː'],
      ['profit','利益','prɑ́fit'],
      ['loss','損失','lɔ́s'],
      ['margin','利益率；差','mɑ́ːrdʒin'],
      ['turnover','売上高；離職率','tə́ːrnòuvər'],
      ['gross','総計の','gróus'],
      ['net','純（利益）','nét'],
      ['asset','資産','ǽset'],
      ['liability','負債','làiəbíləti'],
      ['investment','投資','invéstmənt'],
      ['capital','資本','kǽpitl'],
      ['cash flow','キャッシュフロー',''],
      ['overhead','諸経費','óuvərhèd'],
      ['quarter','四半期','kwɔ́ːrtər'],
      ['fiscal year','会計年度',''],
      ['forecast','予測','fɔ́ːrkæ̀st'],
      ['projection','予測；計画','prədʒékʃən'],
      ['strategy','戦略','strǽtədʒi'],
      ['initiative','取り組み','iníʃiətiv'],
      ['objective','目標','əbdʒéktiv'],
      ['milestone','重要な節目','máilstòun'],
      ['benchmark','基準','béntʃmàːrk'],
      ['performance','実績','pərfɔ́ːrməns'],
      ['productivity','生産性','prɑ̀dʌktívəti'],
      ['efficiency','効率','ifíʃənsi'],
      ['quality','品質','kwɑ́ləti'],
      ['standard','基準','stǽndərd'],
      ['compliance','法令遵守','kəmpláiəns'],
      ['regulation','規制','règjuléiʃən'],
      ['policy','方針','pɑ́ləsi'],
      ['guideline','ガイドライン','gáidlàin'],
      ['protocol','プロトコル；手順','próutəkɔ̀l'],
      ['merger','合併','mə́ːrdʒər'],
      ['acquisition','買収','ækwizíʃən'],
      ['subsidiary','子会社','səbsídiéri'],
      ['affiliate','関連会社','əfílieit'],
      ['stakeholder','利害関係者','stéikhòuldər'],
      ['shareholder','株主','ʃέərhòuldər'],
      ['board of directors','取締役会',''],
      ['chief executive officer','最高経営責任者',''],
      ['human resources','人事部',''],
      ['public relations','広報',''],
      ['marketing','マーケティング','mɑ́ːrkitiŋ'],
      ['advertising','広告','ǽdvərtàiziŋ'],
      ['brand','ブランド','brǽnd'],
      ['campaign','キャンペーン','kæmpéin'],
      ['target audience','ターゲット層',''],
      ['market share','市場シェア',''],
      ['competitor','競合他社','kəmpétitər'],
      ['supply chain','サプライチェーン',''],
      ['logistics','物流','ləudʒístiks'],
      ['warehouse','倉庫','wέərhaus'],
      ['inventory','在庫','ínvəntɔ̀ːri'],
      ['shortage','不足','ʃɔ́ːrtidʒ'],
      ['surplus','余剰','sə́ːrpləs'],
      ['demand','需要','dimǽnd'],
      ['negotiation','交渉','nigòuʃiéiʃən'],
      ['agreement','合意','əgríːmənt'],
      ['terms','条件','tə́ːrmz'],
      ['clause','条項','klɔ́ːz'],
      ['penalty','ペナルティ','pénlti'],
      ['warranty','保証','wɔ́rənti'],
      // 形容詞・副詞
      ['competitive','競争力のある','kəmpétətiv'],
      ['profitable','利益の出る','prɑ́fitəbl'],
      ['sustainable','持続可能な','səstéinəbl'],
      ['innovative','革新的な','ínəvèitiv'],
      ['comprehensive','包括的な','kɑ̀mprihénsiv'],
      ['strategic','戦略的な','strətíːdʒik'],
      ['preliminary','予備的な','priléminèri'],
      ['tentative','暫定的な','téntətiv'],
      ['mutual','相互の','mjúːtʃuəl'],
      ['pending','保留中の','péndiŋ'],
      ['outstanding','未払いの；優れた','àutstǽndiŋ'],
      ['overdue','期限切れの','òuvərdjúː'],
      ['quarterly','四半期ごとの','kwɔ́ːrtərli'],
      ['fiscal','会計の','fískəl'],
      ['confidential','機密の','kɑ̀nfidénʃəl'],
      ['mandatory','義務的な','mǽndətɔ̀ːri'],
      ['voluntary','自発的な','vɑ́ləntèri'],
      ['effective immediately','即時有効で',''],
      ['subject to','〜を条件として',''],
      ['in accordance with','〜に従って',''],
      ['on behalf of','〜を代表して',''],
      ['as per','〜に従って',''],
      ['prior to','〜の前に',''],
      ['subsequent to','〜の後で',''],
      ['in light of','〜を踏まえて',''],
      ['with respect to','〜に関して',''],
    ]
  },

  // ────────────────────────────
  //  TOEIC 900点目標
  // ────────────────────────────
  {
    id: 'toeic-900',
    name: 'TOEIC 900点目標',
    icon: 'crown',
    color: '#3b0764',
    description: 'TOEIC 900点超えを狙う上級ビジネス語彙。金融・法務・経営の高難度語。',
    words: [
      // 動詞
      ['accelerate','加速する','ækséləreit'],
      ['arbitrate','仲裁する','ɑ́ːrbitrèit'],
      ['consolidate','統合する','kənsɑ́lideit'],
      ['curtail','削減する','kəːrtéil'],
      ['depreciate','減価償却する','dipríːʃieit'],
      ['divest','売却する','daivést'],
      ['endorse','支持する；裏書きする','indɔ́ːrs'],
      ['expedite','促進する','ékspiˌdaɪt'],
      ['facilitate','促進する','fəsíliteit'],
      ['foreclose','差し押さえる','fɔːrklóuz'],
      ['incentivize','動機付ける','inséntəvaiz'],
      ['indemnify','補償する','indémnifai'],
      ['leverage','活用する','lévəridʒ'],
      ['liquidate','清算する','líkwideit'],
      ['mitigate','軽減する','mítigeit'],
      ['mobilize','動員する','móubəlaiz'],
      ['overhaul','全面見直しする','óuvərhɔ̀ːl'],
      ['ratify','批准する','rǽtifai'],
      ['reallocate','再配分する','rìːǽləkeit'],
      ['rectify','修正する','réktifai'],
      ['reinstate','復職させる','rìːinstéit'],
      ['remediate','改善する','rimíːdieit'],
      ['repeal','廃止する','ripíːl'],
      ['rescind','無効にする','risínd'],
      ['restructure','再構築する','rìːstrʌ́ktʃər'],
      ['revoke','取り消す','rivóuk'],
      ['sanction','制裁する；承認する','sǽŋkʃən'],
      ['scrutinize','精査する','skrúːtənaiz'],
      ['streamline','効率化する','stríːmlàin'],
      ['supersede','取って代わる','sùːpərsíːd'],
      ['underwrite','引き受ける','ʌ́ndərrìt'],
      ['validate','証明する','vǽlideit'],
      ['waive','放棄する','wéiv'],
      ['withhold','差し控える','wiθhóuld'],
      ['write off','償却する',''],
      ['yield','産出する','jíːld'],
      ['abide by','〜を遵守する',''],
      ['bench','一時休止させる',''],
      ['claw back','回収する',''],
      ['factor in','考慮に入れる',''],
      ['flag','フラグを立てる',''],
      ['hedge','ヘッジする；リスク回避する',''],
      ['ring-fence','保護する',''],
      ['scale back','縮小する',''],
      ['spin off','分社化する',''],
      ['wind down','段階的に縮小する',''],
      // 名詞
      ['amortization','償却','æ̀mərtizéiʃən'],
      ['arbitration','仲裁','ɑ̀ːrbitréiʃən'],
      ['audit','監査','ɔ́ːdit'],
      ['breach','違反','bríːtʃ'],
      ['collateral','担保','kəlǽtərəl'],
      ['commodity','商品','kəmɑ́dəti'],
      ['compliance','法令遵守','kəmpláiəns'],
      ['consortium','コンソーシアム','kənsɔ́ːrʃiəm'],
      ['contingency','不測の事態','kəntíndʒənsi'],
      ['covenant','契約条項','kʌ́vənənt'],
      ['depreciation','減価償却','dipríːʃiéiʃən'],
      ['derivative','金融派生商品','dərívətiv'],
      ['divestiture','売却','daivéstitʃər'],
      ['dividend','配当金','dívədènd'],
      ['due diligence','事前調査',''],
      ['earnings per share','1株当たり利益',''],
      ['encumbrance','抵当権','inkʌ́mbrəns'],
      ['equity','株主資本；公平','ékwiti'],
      ['escrow','エスクロー','éskrou'],
      ['fiduciary','受託者；受託の','fidjúːʃiæ̀ri'],
      ['foreclosure','差し押さえ','fɔːrklóuʒər'],
      ['goodwill','のれん（無形資産）','gúdwìl'],
      ['hedge fund','ヘッジファンド',''],
      ['indemnity','補償','indémnəti'],
      ['injunction','差し止め命令','indʒʌ́ŋkʃən'],
      ['insolvency','支払い不能','insɑ́lvənsi'],
      ['intellectual property','知的財産',''],
      ['jurisdiction','管轄','dʒùərisdíkʃən'],
      ['leverage','レバレッジ','lévəridʒ'],
      ['liquidation','清算','lìkwidéiʃən'],
      ['litigation','訴訟','lìtigéiʃən'],
      ['mandate','委任；命令','mǽndeit'],
      ['moratorium','支払猶予','mɔ̀ːrətɔ́ːriəm'],
      ['negligence','過失','néglidʒəns'],
      ['non-disclosure agreement','秘密保持契約',''],
      ['overhead','諸経費','óuvərhèd'],
      ['penalty clause','違約条項',''],
      ['plaintiff','原告','pléintif'],
      ['precedent','判例','présidənt'],
      ['procurement','調達','prəkjúərmənt'],
      ['provision','引当金；条項','prəvíʒən'],
      ['proxy','代理人；委任状','prɑ́ksi'],
      ['receivership','管財人制度','risíːvərʃip'],
      ['reconciliation','和解；差し引き照合','rèkənsìliéiʃən'],
      ['redundancy','余剰人員','ridʌ́ndənsi'],
      ['remuneration','報酬','rimjùːnəréiʃən'],
      ['restitution','返還；補償','rèstitjúːʃən'],
      ['return on investment','投資利回り',''],
      ['severance','退職金','sévərəns'],
      ['solvency','支払い能力','sɑ́lvənsi'],
      ['statute','法規','stǽtʃuːt'],
      ['subpoena','召喚状','səbpíːnə'],
      ['subsidiary','子会社','səbsídiéri'],
      ['sunk cost','埋没費用',''],
      ['takeover','買収','téikòuvər'],
      ['trademark','商標','tréidmàːrk'],
      ['valuation','評価額','vǽljuéiʃən'],
      ['venture capital','ベンチャーキャピタル',''],
      ['working capital','運転資本',''],
      ['write-off','償却','ráitɔ̀f'],
      // 形容詞・副詞
      ['accrued','未払いの，発生した','əkrúːd'],
      ['binding','法的拘束力のある','báindiŋ'],
      ['callable','繰上償還可能な','kɔ́ːləbl'],
      ['commensurate','釣り合った','kəménʃərət'],
      ['contingent','偶発的な','kəntíndʒənt'],
      ['delinquent','延滞の','dilíŋkwənt'],
      ['discretionary','裁量の','diskréʃənèri'],
      ['fiduciary','受託者としての','fidjúːʃiæ̀ri'],
      ['fungible','代替可能な','fʌ́ndʒəbl'],
      ['indemnified','補償された','indémnifàid'],
      ['interim','暫定的な','íntərim'],
      ['irrevocable','取り消せない','irévəkəbl'],
      ['leveraged','レバレッジのかかった','lévəridʒd'],
      ['liquidated','清算された','líkwidèitid'],
      ['material','重大な；実質的な','mətíəriəl'],
      ['nominal','名目上の','nɑ́minəl'],
      ['non-compete','競業禁止の',''],
      ['null and void','無効の',''],
      ['on a pro-rata basis','按分比例で',''],
      ['proprietary','専有の','prəpráiətèri'],
      ['punitive','懲罰的な','pjúːnitiv'],
      ['statutory','法定の','stǽtʃutɔ̀ːri'],
      ['subject to change','変更の余地がある',''],
      ['transparent','透明な','trǽnspærənt'],
      ['unilateral','一方的な','jùːnilǽtərəl'],
      ['vested','既得の','véstid'],
      ['viable','実行可能な','váiəbl'],
      ['void','無効な','vɔ́id'],
      ['waivable','放棄可能な','wéivəbl'],
      ['with prejudice','不利益付きで（訴権喪失）',''],
      ['without prejudice','権利留保付きで',''],
    ]
  }

];
